name: LeshaAndGleb_test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install python for test charge
      run:  sudo apt install python3-pip
    - uses: actions/checkout@v2
    - name: install teleBot
      run: python pip install pyTelegramBotAPI
    - name: Run Test
      working-directory: ./tests
      run: python ./studtest.py
